# Generated by Django 6.0.2 on 2026-03-11 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='category',
            field=models.CharField(choices=[('electrical', '⚡ Electrical'), ('plumbing', '🔧 Plumbing / Water'), ('internet', '🌐 Internet / Network'), ('ac', '❄️ Air Conditioning'), ('furniture', '🪑 Furniture / Equipment'), ('security', '🔒 Security'), ('cleanliness', '🧹 Cleanliness'), ('other', '📌 Other')], default='other', max_length=20),
        ),
    ]
