# Generated by Django 6.0.2 on 2026-03-05 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0002_issue_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending (รอการตรวจสอบ)'), ('in_progress', 'In Progress (กำลังดำเนินการ)'), ('resolved', 'Resolved (แก้ไขแล้ว)'), ('rejected', 'Rejected (ปฏิเสธ/ยกเลิก)')], default='pending', max_length=20),
        ),
    ]
