# Generated by Django 6.0.2 on 2026-03-11 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0002_alter_issue_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='issuestatuslog',
            old_name='comment',
            new_name='note',
        ),
    ]
