# Generated by Django 6.0.2 on 2026-03-05 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0002_issue_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='confirmed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='issue',
            name='resolved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='issue',
            name='status',
            field=models.CharField(choices=[('pending', 'รอการถูกยืนยัน'), ('confirmed', 'รับเรื่องแล้ว'), ('resolved', 'แก้ไขเสร็จสิ้น')], default='pending', max_length=20),
        ),
    ]
