# Generated by Django 6.0.2 on 2026-03-11 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0003_issue_confirmed_at_issue_resolved_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='issue',
            name='confirmed_at',
        ),
        migrations.RemoveField(
            model_name='issue',
            name='resolved_at',
        ),
        migrations.AddField(
            model_name='issue',
            name='category',
            field=models.CharField(choices=[('electrical', '⚡ Electrical'), ('plumbing', '🔧 Plumbing / Water'), ('internet', '🌐 Internet / Network'), ('ac', '❄️ Air Conditioning'), ('furniture', '🪑 Furniture / Equipment'), ('security', '🔒 Security'), ('cleanliness', '🧹 Cleanliness'), ('other', '📌 Other')], default='other', max_length=20),
        ),
        migrations.AlterField(
            model_name='issue',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending (รอการตรวจสอบ)'), ('in_progress', 'In Progress (กำลังดำเนินการ)'), ('resolved', 'Resolved (แก้ไขแล้ว)'), ('rejected', 'Rejected (ปฏิเสธ/ยกเลิก)')], default='pending', max_length=20),
        ),
    ]
