# Generated by Django 6.0.2 on 2026-03-05 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0003_alter_issue_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='rejection_reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
