# Generated by Django 6.0.2 on 2026-03-11 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0003_rename_comment_issuestatuslog_note'),
    ]

    operations = [
        migrations.CreateModel(
            name='HotspotCoordinate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zone', models.CharField(choices=[('archif1', 'คณะสถาปัตยกรรม ชั้น 1'), ('archif2', 'คณะสถาปัตยกรรม ชั้น 2'), ('archif3', 'คณะสถาปัตยกรรม ชั้น 3'), ('archif4', 'คณะสถาปัตยกรรม ชั้น 4'), ('archif5', 'คณะสถาปัตยกรรม ชั้น 5'), ('archif6', 'คณะสถาปัตยกรรม ชั้น 6'), ('outdoor81', 'ลานหน้าตึก 81')], help_text='โซนหรือชั้นที่จุดนี้อยู่', max_length=20)),
                ('keyword', models.CharField(help_text="คำสำคัญ เช่น 'ห้องน้ำชาย', 'ลิฟต์', 'บันไดหนีไฟ'", max_length=100)),
                ('position', models.CharField(help_text='พิกัด position (x y z) ที่ได้จากเครื่องมือ', max_length=100)),
                ('normal', models.CharField(default='0.0000 1.0000 0.0000', help_text='พิกัด normal (x y z) ที่ได้จากเครื่องมือ', max_length=100)),
            ],
        ),
    ]
